### ISSUE TITLE
Please consider inlining the lens definitions for day 21

### ISSUE THREAD

**Issue by joneshf** [paf31/24-days-of-purescript-2016#6]
I'm posting this here since I'm unsure how gist notifications work and I don't know how to request a merge of a gist fork :man_shrugging:. Please close it if it's the wrong place.

Just saw day 21, and it's great! As pointed out, the last example can't run since there's no lens for try ps. I forked @FrigoEU's gist and inlined the definitions and it seems to work: http://try.purescript.org/?gist=543c99d17de788c8be2e2d3a9b14d6c9.

@FrigoEU, are you up for taking the changes to your gist so we can see your example on try ps? If not, I can make a PR here to add the link to the post if that's acceptable.

**Comment by FrigoEU** [comment]
Huh, that never even occured to me... Very good idea. I updated my gist.

@paf31, could you change the link from gist to Try PureScript? http://try.purescript.org/?gist=441b45128d24b5964bfff7443417160b

**Comment by paf31** [comment]
Yes, can do. Thank you both.
